import Link from "next/link";
import { ArrowDownRight, ArrowUpRight, Bot, BrainCircuit, Code2, Compass, Workflow } from "lucide-react";

const services = [
  {number: "01", label: "Applied AI", title: "AI systems that hold up in the real world.", description: "From LLM applications and retrieval systems to evaluation and observability, we take AI beyond the demo and into production.", icon: BrainCircuit, tags: ["LLM products", "RAG systems", "AI evaluation"]},
  {number: "02", label: "Automation", title: "Turn repetitive work into intelligent flow.", description: "We map the work, find the friction, and build reliable automations that connect your tools, data, and people.", icon: Workflow, tags: ["AI agents", "Workflow design", "Integrations"]},
  {number: "03", label: "Software", title: "Build the product your future needs.", description: "High-quality web, mobile, and backend systems designed around clear product thinking, strong foundations, and measurable outcomes.", icon: Code2, tags: ["Web platforms", "Mobile apps", "Backend systems"]},
  {number: "04", label: "Direction", title: "Make the next technical decision count.", description: "A senior partner for AI strategy, architecture, technical due diligence, and the hard choices between idea and execution.", icon: Compass, tags: ["AI strategy", "Architecture", "Technical leadership"]},
];

export default function ServicesPage() {
  return <main>
    <section className="ai-services-hero animate-on-scroll"><div className="ai-services-orbit orbit-a"/><div className="ai-services-orbit orbit-b"/><div className="container ai-services-hero-grid"><div><div className="eyebrow ai-eyebrow"><span className="status-dot"/> AI-first engineering studio</div><h1>We go deep on <span>AI.</span></h1><p>We design intelligent systems, automate meaningful work, and build the software that makes ambitious ideas real.</p><div className="hero-actions"><Link href="#service-paths" className="button-light">Choose your path <ArrowDownRight size={15}/></Link><Link href="/contact" className="ai-hero-link">Talk to an AI engineer <ArrowUpRight size={15}/></Link></div></div><div className="ai-services-signal"><div className="signal-header"><span>DEVTECH AI / FOCUS AREAS</span><span>2026</span></div><div className="signal-core"><Bot size={25}/><strong>Intelligence<br/><em>in practice.</em></strong></div><div className="signal-lines"><div><span>01</span><b>Reasoning systems</b></div><div><span>02</span><b>Workflow automation</b></div><div><span>03</span><b>Software foundations</b></div></div></div></div></section>
    <section className="ai-services-manifesto animate-on-scroll delay-1"><div className="container ai-services-manifesto-grid"><div className="eyebrow">The DevTech AI difference</div><h2>AI is not a feature we bolt on. <span>It is how we think about the whole system.</span></h2><p>Useful intelligence lives at the intersection of models, data, interfaces, infrastructure, and human behavior. That is where we work.</p></div></section>
    <section id="service-paths" className="section ai-service-paths animate-on-scroll delay-1"><div className="container"><div className="section-head"><div><div className="eyebrow">Choose your starting point</div><h2>Where should we go deep?</h2></div><p className="section-intro">Start with the problem closest to you. We’ll help shape the right technical path from there.</p></div><div className="ai-service-grid">{services.map(({number, label, title, description, icon: Icon, tags}) => <article className="ai-service-card" key={number}><div className="ai-service-card-top"><span className="ai-service-number">{number}</span><span className="ai-service-icon"><Icon size={19}/></span></div><div><div className="eyebrow">{label}</div><h3>{title}</h3><p>{description}</p></div><div className="ai-service-tags">{tags.map((tag) => <span key={tag}>{tag}</span>)}</div><Link href={`/contact?service=${encodeURIComponent(label)}`} className="ai-service-link">Explore this path <ArrowUpRight size={15}/></Link></article>)}</div></div></section>
    <section className="section section-tint ai-delivery-section animate-on-scroll delay-1"><div className="container capability-layout"><div><div className="eyebrow">How deep work gets shipped</div><h2>Clarity, then intelligence, then momentum.</h2></div><div className="ai-delivery-steps"><div><span>01</span><div><h3>Understand the work</h3><p>We learn the users, constraints, data, and business outcome before reaching for a model.</p></div></div><div><span>02</span><div><h3>Design the system</h3><p>We choose the right blend of models, software, automation, and human judgment.</p></div></div><div><span>03</span><div><h3>Make it dependable</h3><p>We evaluate, instrument, and iterate until the system earns trust in the workflow.</p></div></div></div></div></section>
    <section className="ai-services-cta animate-on-scroll delay-1"><div className="container"><div><div className="eyebrow">Have a hard problem?</div><h2>Bring us the part that doesn’t fit in a template.</h2></div><Link className="button-dark" href="/contact">Start with your problem <ArrowUpRight size={15}/></Link></div></section>
  </main>;
}
