import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight, Check } from "lucide-react";
import { notFound } from "next/navigation";
import { getJobBySlug } from "@/lib/db";

export async function generateMetadata({params}: {params: Promise<{slug: string}>}): Promise<Metadata> { const {slug} = await params; const job = await getJobBySlug(slug); return {title: job ? `${job.title} | DevTech AI Careers` : "Position not found", description: job?.description, alternates: {canonical: `/careers/${slug}`}, openGraph: {title: job?.title, description: job?.description, type: "website"}}; }

export default async function JobPage({params}: {params: Promise<{slug: string}>}) { const {slug} = await params; const job = await getJobBySlug(slug); if (!job) notFound(); return <main><section className="page-hero"><div className="container"><div className="eyebrow">DevTech AI careers · {job.department}</div><h1>{job.title}</h1><p>{job.description}</p></div></section><section className="section"><div className="container job-layout"><article className="job-content"><h2>About the role</h2><p>{job.description} You’ll work closely with a small product team where your decisions are visible, your questions are welcome, and the distance between an idea and a shipped feature is short.</p><h2>What you’ll do</h2><ul>{job.responsibilities.map((item) => <li key={item}>{item}</li>)}</ul><h2>What you bring</h2><ul>{job.requirements.map((item) => <li key={item}>{item}</li>)}</ul><h2>Nice to have</h2><ul>{job.niceToHave.map((item) => <li key={item}>{item}</li>)}</ul><h2>What you’ll learn and work on</h2><p>You’ll see how a real product moves from a user need to a tested, observable release. Along the way, you’ll work with experienced engineers, make tradeoffs in the open, and build a portfolio of work you can be proud of.</p></article><aside className="job-sidebar"><dl><dt>Location</dt><dd>{job.location}</dd><dt>Work arrangement</dt><dd>{job.workMode}</dd><dt>Employment</dt><dd>{job.employmentType}</dd><dt>Duration</dt><dd>{job.duration}</dd><dt>Posted</dt><dd>{new Date(job.publishedAt).toLocaleDateString("en-US", {month: "long", day: "numeric", year: "numeric"})}</dd></dl><Link href={`/careers/${job.slug}/apply`} className="button-dark">Apply for this role <ArrowUpRight size={15}/></Link>{job.compensationType === "Unpaid" ? <div className="unpaid-note"><strong>Compensation</strong><br/>{job.compensationText}</div> : <div className="unpaid-note" style={{background: "#eef4f0", borderColor: "var(--line)", color: "var(--green)"}}><strong>Compensation</strong><br/>{job.compensationText}</div>}<div style={{marginTop: 24, display: "grid", gap: 10}}>{job.skills.map((skill) => <div key={skill} style={{fontSize: 13, display: "flex", gap: 9, color: "var(--muted)"}}><Check size={15} color="#2f5749"/>{skill}</div>)}</div></aside></div></section></main>; }
