"use client";
import { useEffect, useState } from "react";
import { ArrowUpRight, Plus, X } from "lucide-react";
import type { Job } from "@/lib/data";

export function AdminJobsClient() {
  const [items, setItems] = useState<Job[]>([]); const [creating, setCreating] = useState(false); const [title, setTitle] = useState(""); const [department, setDepartment] = useState("Product engineering"); const [error, setError] = useState("");
  async function load() { const response = await fetch("/api/jobs?admin=true", {cache: "no-store"}); const result = await response.json(); if (!response.ok) {setError(result.error || "Unable to load jobs."); return;} setItems(result.jobs || []); }
  useEffect(() => { load(); }, []);
  async function create() { if (!title.trim()) return; const response = await fetch("/api/jobs", {method: "POST", headers: {"Content-Type": "application/json"}, body: JSON.stringify({title, department, slug: title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "-"), description: `Join DevTech AI as a ${title}.`})}); const result = await response.json(); if (!response.ok) {setError(result.error || "Unable to create job."); return;} setTitle(""); setCreating(false); await load(); }
  async function setStatus(id: string, status: Job["status"]) { const response = await fetch(`/api/jobs/${id}`, {method: "PATCH", headers: {"Content-Type": "application/json"}, body: JSON.stringify({status})}); if (!response.ok) {const result = await response.json(); setError(result.error || "Unable to update job."); return;} await load(); }
  return <><div className="admin-toolbar"><div><input placeholder="Search jobs" /></div><button className="button-dark" onClick={() => setCreating(true)}><Plus size={15}/> New job</button></div>{error && <p style={{color: "#a14e40", fontSize: 13}}>{error}</p>}{creating && <div className="admin-panel" style={{marginBottom: 15}}><div className="admin-toolbar"><h2 style={{margin: 0}}>Create a position</h2><button className="button-small" onClick={() => setCreating(false)}><X size={15}/></button></div><div className="field-grid"><div className="field"><label>Job title *</label><input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="e.g. Product designer" /></div><div className="field"><label>Department</label><select value={department} onChange={(e) => setDepartment(e.target.value)}><option>Product engineering</option><option>Systems engineering</option><option>Operations</option></select></div></div><button className="button-dark" onClick={create}>Save as draft <ArrowUpRight size={15}/></button></div>}<div className="admin-panel"><h2>All jobs <span style={{color: "var(--muted)", fontSize: 13, fontFamily: "var(--sans)"}}>({items.length})</span></h2><table className="admin-table"><thead><tr><th>Position</th><th>Department</th><th>Location</th><th>Status</th><th>Published</th><th></th></tr></thead><tbody>{items.map((job) => <tr key={job.id}><td><strong>{job.title}</strong><br/><span style={{color: "var(--muted)", fontSize: 11}}>/{job.slug}</span></td><td>{job.department}</td><td>{job.location}</td><td><select className="button-small" value={job.status} onChange={(e) => setStatus(job.id, e.target.value as Job["status"])}><option>draft</option><option>open</option><option>paused</option><option>closed</option></select></td><td>{job.publishedAt || "—"}</td><td><button className="button-small">Edit</button></td></tr>)}</tbody></table></div></>;
}
