import { NextResponse } from "next/server";
import { getAdminJobs, getPublishedJobs } from "@/lib/db";
import { requireAdminApi } from "@/lib/auth";

export const runtime = "nodejs";
const errorResponse = (error: unknown) => NextResponse.json({error: error instanceof Error ? error.message : "Request failed."}, {status: error instanceof Error && error.message === "UNAUTHORIZED" ? 401 : 400});

export async function GET(request: Request) { try { const isAdmin = new URL(request.url).searchParams.get("admin") === "true"; if (isAdmin) { await requireAdminApi(); return NextResponse.json({jobs: await getAdminJobs()}); } return NextResponse.json({jobs: await getPublishedJobs()}); } catch (error) { return errorResponse(error); } }
export async function POST(request: Request) { try { const {supabase} = await requireAdminApi(); const body = await request.json(); if (!body.title || !body.slug || !body.description || !body.department) return NextResponse.json({error: "title, slug, description, and department are required."}, {status: 422}); const {data, error} = await supabase.from("jobs").insert({title: String(body.title).trim(), slug: String(body.slug).trim(), department: String(body.department).trim(), description: String(body.description).trim(), responsibilities: body.responsibilities || [], requirements: body.requirements || [], nice_to_have: body.niceToHave || [], location: body.location || "Remote", work_mode: body.workMode || "Remote", employment_type: body.employmentType || "Full-time", duration: body.duration || "Permanent", compensation_type: body.compensationType || "Paid", compensation_text: body.compensationText || "Details shared during the process.", skills: body.skills || [], published_at: body.status === "open" ? new Date().toISOString().slice(0,10) : null, deadline: body.deadline || null, status: body.status || "draft"}).select().single(); if (error) throw error; return NextResponse.json({job: data}, {status: 201}); } catch (error) { return errorResponse(error); } }
